"""added basic schema and new columns to the table 

Revision ID: 21ebc8dbdf1a
Revises: 4db4fc173f79
Create Date: 2026-03-12 17:53:12.696269

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ebc8dbdf1a'
down_revision: Union[str, Sequence[str], None] = '4db4fc173f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
