"""added basic schema and new columns to the table 

Revision ID: 4db4fc173f79
Revises: 415dc62d9b49
Create Date: 2026-03-12 17:28:35.910466

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4db4fc173f79'
down_revision: Union[str, Sequence[str], None] = '415dc62d9b49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('post', sa.Column('excerpt', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('post', sa.Column('date', sa.DateTime(), nullable=False))
    op.add_column('post', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('post', sa.Column('readingTime', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('post', sa.Column('fatured', sa.Boolean(), nullable=False))
    op.alter_column('post', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('post', 'fatured')
    op.drop_column('post', 'readingTime')
    op.drop_column('post', 'category')
    op.drop_column('post', 'date')
    op.drop_column('post', 'excerpt')
    op.drop_column('post', 'slug')
    # ### end Alembic commands ###
